import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, GraduationCap, MapPin } from "lucide-react";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/PortfolioPages.module.css";

const items=[
["Dec 2025 – Jun 2026","Huawei (Via Premier Service & Recruitment)","Linux & Database Administrator","Cairo, Egypt (Onsite)","Linux, Databases, Monitoring, Telecom","Worked in a UAE telecom client environment (du), involved in system monitoring, incident and change management, log analysis and reporting."],
["Aug 2024 – Oct 2024","German University in Cairo (GUC)","Flutter Developer Intern","Cairo, Egypt","Flutter, Firebase, Dart, Mobile","Developed a mobile application as part of an internship, gaining hands-on experience in Flutter development and Firebase integration."],
["Jun 2024 – Aug 2024","ESG & Company","Flutter Developer Intern","Cairo, Egypt","Flutter, Firebase, App Development","Worked on a Flutter mobile application for environmental data management, focusing on real-world data integration and user-centric design."],
["Mar 2025","Egyptian Electrical Solution (EES)","Flutter App & Web Developer Intern","Cairo, Egypt","Flutter, Firebase, Web Dashboard","Built a Flutter mobile app and a web dashboard using Firebase, contributing to a complete full-stack solution."],
["2023","MIE Competition – Stuttgart","Participant","Stuttgart, Germany","Competition, Innovation, Teamwork","Participated in the Microsoft Innovation in Education competition, working on innovative technology solutions."]
];
export default function Experience(){return <PageFrame active="Experience"><main className={styles.container}>
<section className={styles.projectPageHero}><div><div className={styles.kicker}>EXPERIENCE & EDUCATION</div><h1 className={styles.sectionTitle} style={{fontSize:54}}>My Journey <span className={styles.gradient}>So Far</span></h1><p className={styles.sectionIntro}>A journey of learning, building and continuously improving. From working in industry to building real-world projects and diving deeper into Machine Learning and AI.</p><div style={{display:"flex",gap:12,marginTop:24}}><a href="/full_stack_cv_edited.pdf" target="_blank" className={styles.button}>Download CV</a><a href="https://www.linkedin.com/in/nardy-attallah" target="_blank" className={styles.buttonGhost}>View LinkedIn <ArrowRight size={14}/></a></div></div><div className={styles.card}><h3>“A little progress every day adds up to big results.”</h3><p>— Nardy Attalla</p></div></section>
<section className={styles.sectionBlock}><div className={styles.split}><div><h2 className={styles.sectionTitle}>Professional Experience</h2><div className={styles.timeline}>{items.map(([date,company,role,place,tags,desc])=><article className={styles.timelineItem} key={company}><div className={styles.timelineDate}>{date}</div><div className={styles.timelineCard}><h3>{role}</h3><div className={styles.sub}>{company} · <MapPin size={10}/> {place}</div><div className={styles.chips}>{tags.split(", ").map(t=><span key={t}>{t}</span>)}</div><p>{desc}</p></div></article>)}</div></div><aside><div className={styles.card}><GraduationCap size={24}/><h3>B.Sc. Computer Science and Engineering</h3><p>German University in Cairo (GUC)<br/>2021 – 2025</p></div><div className={styles.card}><BriefcaseBusiness size={24}/><h3>4+ Professional & Internship Experiences</h3><p>Software engineering, mobile development and production operations.</p></div></aside></div></section>
<section className={styles.sectionBlock}><h2 className={styles.sectionTitle}>Education</h2><div className={styles.card}><h3>German University in Cairo (GUC)</h3><p>B.Sc. Computer Science and Engineering · 2021 – 2025</p><div className={styles.chips}><span>Computer Science</span><span>Software Engineering</span><span>Machine Learning</span></div></div></section>
</main></PageFrame>}