import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BriefcaseBusiness, GraduationCap, MapPin, Target, Award, BookOpen } from "lucide-react";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/PortfolioPages.module.css";

const items=[
["Dec 2025 – Jun 2026","Huawei (Via Premier Service & Recruitment)","Linux & Database Administrator","Cairo, Egypt (Onsite)","Linux, Databases, Monitoring, Telecom","Worked in a UAE telecom client environment (du), involved in system monitoring, incident and change management, log analysis and reporting."],
["Aug 2024 – Oct 2024","German University in Cairo (GUC)","Flutter Developer Intern","Cairo, Egypt","Flutter, Firebase, Dart, Mobile","Developed a mobile application as part of an internship, gaining hands-on experience in Flutter development and Firebase integration."],
["Jun 2024 – Aug 2024","ESG & Company","Flutter Developer Intern","Cairo, Egypt","Flutter, Firebase, App Development","Worked on a Flutter mobile application for environmental data management, focusing on real-world data integration and user-centric design."],
["Mar 2025","Egyptian Electrical Solution (EES)","Flutter App & Web Developer Intern","Cairo, Egypt","Flutter, Firebase, Web Dashboard","Built a Flutter mobile app and a web dashboard using Firebase, contributing to a complete full-stack solution."],
["2023","MIE Competition – Stuttgart","Participant","Stuttgart, Germany","Competition, Innovation, Teamwork","Participated in the Microsoft Innovation in Education competition, working on innovative technology solutions."]
];

export default function Experience(){return <PageFrame active="Experience"><main className={styles.container}>
<section className={styles.projectPageHero}><div><div className={styles.kicker}>EXPERIENCE &amp; EDUCATION</div><h1 className={styles.sectionTitle} style={{fontSize:54}}>My Journey <span className={styles.gradient}>So Far</span></h1><p className={styles.sectionIntro}>A journey of learning, building and continuously improving. From working in industry to building real-world projects and diving deeper into Machine Learning and AI — every step has shaped what I want to build next.</p><div className={styles.heroButtons}><a href="/full_stack_cv_edited.pdf" target="_blank" className={styles.button}>Download CV</a><a href="https://www.linkedin.com/in/nardy-attallah" target="_blank" rel="noreferrer" className={styles.buttonGhost}>View LinkedIn <ArrowRight size={14}/></a></div></div><div className={styles.experienceHeroVisual}><Image src="/Distance_stereo.jpeg" alt="" fill sizes="500px"/><div>“A little progress every day adds up to big results.”<small>— Nardy Attalla</small></div></div></section>

<section className={styles.sectionBlock}><div className={styles.experienceLayout}><div><div className={styles.sectionLabel}><BriefcaseBusiness/><h2>Professional Experience</h2><span>Real experience. Real impact.</span></div><div className={styles.timeline}>{items.map(([date,company,role,place,tags,desc])=><article className={styles.timelineItem} key={company}><div className={styles.timelineDate}>{date}</div><div className={styles.timelineCard}><div className={styles.timelineTop}><div><h3>{role}</h3><div className={styles.sub}>{company}</div></div><span><MapPin size={11}/> {place}</span></div><div className={styles.chips}>{tags.split(", ").map(t=><span key={t}>{t}</span>)}</div><p>{desc}</p></div></article>)}</div></div><aside className={styles.quickFacts}><h3>Quick Facts</h3><div><BriefcaseBusiness/><b>4+</b><span>Professional &amp; Internship Experiences</span></div><div><Target/><b>10+</b><span>Projects Completed</span></div><div><GraduationCap/><b>B.Sc.</b><span>Computer Science and Engineering (GUC)</span></div><div><MapPin/><b>Cairo, Egypt</b><span>Open to opportunities worldwide</span></div></aside></div></section>

<section className={styles.sectionBlock}><div className={styles.sectionLabel}><GraduationCap/><h2>Education</h2></div><div className={styles.educationGrid}><div className={styles.card}><h3>German University in Cairo (GUC)</h3><p>B.Sc. Computer Science and Engineering · 2021 – 2025</p><div className={styles.chips}><span>Computer Science</span><span>Software Engineering</span><span>Machine Learning</span></div><p>Studied software systems, algorithms, databases, machine learning and emerging technologies. Graduated in July 2025.</p></div><div className={styles.coursework}><h3><BookOpen size={17}/> Relevant Coursework</h3>{["Data Structures & Algorithms","Machine Learning","Computer Vision","Databases","Software Engineering","Computer Networks"].map(x=><span key={x}>{x}</span>)}</div></div></section>

<section className={styles.sectionBlock}><div className={styles.sectionLabel}><Award/><h2>Certifications &amp; Learning</h2><span>Always learning. Always improving.</span></div><div className={styles.certGrid}>{["IBM AI Workflow Specialization","Machine Learning Specialization","Building AI — University of Helsinki","SQL — SoloLearn"].map(x=><div className={styles.certCard} key={x}><Award size={22}/><h3>{x}</h3><p>Learning &amp; professional development</p><a href="/full_stack_cv_edited.pdf" target="_blank">View Certificate <ArrowRight size={12}/></a></div>)}</div></section>
</main></PageFrame>}