"use client";
import type { ReactNode } from "react";
import { Github, Linkedin, Mail, MapPin, ArrowRight, BriefcaseBusiness, Users, Lightbulb, LockKeyhole } from "lucide-react";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/PortfolioPages.module.css";

export default function Contact(){return <PageFrame active="Contact"><main className={styles.container}>
<section className={styles.contactHero}><div><div className={styles.kicker}>LET’S CONNECT</div><h1 className={styles.sectionTitle} style={{fontSize:54}}>Let’s Build<br/>What’s <span className={styles.gradient}>Next</span></h1><p className={styles.sectionIntro}>I’m always open to new opportunities, interesting projects, collaborations, or a friendly chat about technology, Machine Learning, or building real-world solutions.</p><div className={styles.contactHighlights}><span><BriefcaseBusiness/>Open to opportunities</span><span><Users/>Interested in collaborations</span><span><Lightbulb/>Happy to exchange ideas</span></div></div><div className={styles.contactHeroArt}><span>Same Engineer.<br/>Bigger Possibilities.</span></div></section>
<section className={styles.sectionBlock}><div className={styles.contactGrid}><div><div className={styles.sectionLabel}><Mail/><h2>Contact Information</h2></div><div className={styles.contactCards}><ContactCard icon={<Mail/>} title="Email" value="nardy.attalla@gmail.com" href="mailto:nardy.attalla@gmail.com"/><ContactCard icon={<Linkedin/>} title="LinkedIn" value="linkedin.com/in/nardy-attallah" href="https://www.linkedin.com/in/nardy-attallah"/><ContactCard icon={<Github/>} title="GitHub" value="github.com/Nardy11" href="https://github.com/Nardy11"/><ContactCard icon={<MapPin/>} title="Location" value="Cairo, Egypt"/></div></div><form className={styles.form} onSubmit={e=>e.preventDefault()}><h2>Send a Message</h2><p>Have a question, an opportunity, or just want to say hi? Drop me a message.</p><div className={styles.formRow}><input placeholder="Your Name"/><input placeholder="Your Email"/></div><input placeholder="Subject"/><textarea placeholder="Your Message"/><button className={styles.button} type="submit" style={{width:"100%",border:0}}>Send Message <ArrowRight size={14}/></button><small className={styles.safeNote}><LockKeyhole size={13}/> Your information is safe with me.</small></form></div></section>
<section className={styles.sectionBlock}><div className={styles.locationGrid}><div><div className={styles.sectionLabel}><MapPin/><h2>Where I’m Based</h2></div><p className={styles.sectionIntro}>Currently in Cairo, Egypt, and open to opportunities worldwide.</p><div className={styles.mapWrap}><iframe title="Cairo, Egypt map" src="https://www.openstreetmap.org/export/embed.html?bbox=31.15%2C29.95%2C31.45%2C30.15&layer=mapnik&marker=30.0444%2C31.2357" style={{border:0,width:"100%",height:"100%"}} loading="lazy"/></div></div><div className={styles.locationCard}><MapPin/><b>Cairo, Egypt</b><span>Open to remote work worldwide</span><a href="https://www.openstreetmap.org/?mlat=30.0444&mlon=31.2357#map=12/30.0444/31.2357" target="_blank" rel="noreferrer">Open Map <ArrowRight size={13}/></a></div></div></section>
<section className={styles.ctaBlock}><div><span>LET’S CREATE SOMETHING MEANINGFUL</span><h2>Whether it’s a project, opportunity, or conversation.</h2><p>I’d love to hear from you.</p></div><a href="mailto:nardy.attalla@gmail.com">Get in Touch <ArrowRight size={15}/></a></section>
</main></PageFrame>}
function ContactCard({icon,title,value,href}:{icon:ReactNode;title:string;value:string;href?:string}){return <div className={styles.contactCard}>{icon}<div><b>{title}</b>{href?<a href={href} target="_blank" rel="noreferrer">{value}</a>:<span>{value}</span>}</div></div>}
