import type { ElementType } from "react";
import Link from "next/link";
import { ArrowRight, Code2, BrainCircuit, Smartphone, Eye, Server, Wrench, MessageCircle } from "lucide-react";
import { SiPython, SiJavascript, SiTypescript, SiDart, SiMysql, SiCplusplus, SiReact, SiNextdotjs, SiNodedotjs, SiExpress, SiTailwindcss, SiHtml5, SiCss3, SiFlutter, SiFirebase, SiExpo, SiScikitlearn, SiTensorflow, SiPytorch, SiPandas, SiNumpy, SiOpencv, SiRos, SiRoboflow, SiNvidia, SiGit, SiDocker, SiLinux, SiAmazon, SiTerraform } from "react-icons/si";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/PortfolioPages.module.css";

const groups=[
["Programming Languages",Code2,"Languages I use to build, solve and experiment.",[[SiPython,"Python"],[SiJavascript,"JavaScript"],[SiTypescript,"TypeScript"],[SiDart,"Dart"],[SiMysql,"SQL"],[SiCplusplus,"C++"]]],
["Web Development",Code2,"Building modern and responsive web applications.",[[SiReact,"React"],[SiNextdotjs,"Next.js"],[SiNodedotjs,"Node.js"],[SiExpress,"Express"],[SiTailwindcss,"Tailwind CSS"],[SiHtml5,"HTML"],[SiCss3,"CSS"]]],
["Mobile Development",Smartphone,"Cross-platform mobile app development.",[[SiFlutter,"Flutter"],[SiFirebase,"Firebase"],[SiReact,"React Native"],[SiExpo,"Expo"]]],
["Machine Learning & Data",BrainCircuit,"From classical ML to deep learning, with hands-on projects.",[[SiScikitlearn,"Scikit-learn"],[SiTensorflow,"TensorFlow"],[SiPytorch,"PyTorch"],[SiPandas,"Pandas"],[SiNumpy,"NumPy"]]],
["Computer Vision",Eye,"Building perception systems and working with real-world data.",[[SiOpencv,"OpenCV"],[SiRoboflow,"YOLOv8"],[SiRos,"ROS"],[SiRoboflow,"Roboflow"],[SiNvidia,"NVIDIA"]]],
["DevOps & Tools",Server,"Tools I use to build, deploy and manage projects.",[[SiGit,"Git"],[SiDocker,"Docker"],[SiLinux,"Linux"],[SiAmazon,"AWS"],[SiTerraform,"Terraform"],[Code2,"VS Code"]]]
];
const roadmap=[["Foundations",["Python","Math & Statistics","Data Analysis"],"done"],["Core ML",["Supervised Learning","Unsupervised Learning","NLP (Basics)","Computer Vision"],"done"],["Advanced (In Progress)",["Deep Learning","MLOps"],"progress"],["Next",["RAG","LLMs","AI Agents"],"next"]];
export default function Skills(){return <PageFrame active="Skills"><main className={styles.container}>
<section className={styles.skillsHero}><div><div className={styles.kicker}>SKILLS &amp; TECHNOLOGIES</div><h1 className={styles.sectionTitle} style={{fontSize:52}}>Tools for Ideas,<br/>Skills for <span className={styles.gradient}>Impact.</span></h1><p className={styles.sectionIntro}>A combination of software engineering, machine learning and problem-solving skills that I use to turn ideas into real-world applications.</p><div className={styles.heroButtons}><Link href="/projects" className={styles.button}>View My Projects <ArrowRight size={14}/></Link><a href="/full_stack_cv_edited.pdf" target="_blank" className={styles.buttonGhost}>Download CV</a></div></div><div className={styles.skillsHeroVisual}><ImageFallback/></div></section>
<section className={styles.sectionBlock}><div className={styles.sectionLabel}><Code2/><h2>Technical Skills</h2><span>A practical toolkit built through university, projects and real-world experience.</span></div><div className={styles.skillsGrid}>{groups.map(([title,Icon,desc,items])=>{const I=Icon as ElementType;return <article className={styles.skillBox} key={String(title)}><I size={25} color="#7296ff"/><h3>{String(title)}</h3><p>{String(desc)}</p><div className={styles.skillItems}>{(items as [ElementType,string][]).map(([Icon,x])=><span key={x}><Icon size={18}/>{x}</span>)}</div></article>})}</div></section>
<section className={styles.sectionBlock}><div className={styles.sectionLabel}><BrainCircuit/><h2>My Machine Learning Journey</h2><span>A visual roadmap of what I’ve learned, what I’m learning, and what’s next.</span></div><div className={styles.roadmapRich}>{roadmap.map(([title,items,state])=><div className={styles.roadGroup} key={title}><h3 className={String(state)}>{title}</h3><div>{items.map(x=><span className={String(state)} key={x}><i/>{x}</span>)}</div></div>)}<div className={styles.progress}><span/><b>65%</b></div><div className={styles.legend}><span>● Completed</span><span>● In Progress</span><span>○ Next</span></div></div></section>
<section className={styles.toolsRow}><div><div className={styles.sectionLabel}><Wrench/><h2>Tools I Use Daily</h2></div><div className={styles.toolChips}>{["VS Code","GitHub","Notion","Postman","Figma","Ubuntu","Docker","Google Colab"].map(x=><span key={x}>{x}</span>)}</div></div><div><div className={styles.sectionLabel}><BrainCircuit/><h2>Currently Learning</h2></div><div className={styles.learningChips}>{["Deep Learning","MLOps","RAG","LLMs","System Design","Cloud Deployment"].map(x=><span key={x}>{x}</span>)}</div></div><blockquote>“Consistency turns learning into results.”<small>— Nardy Attalla</small></blockquote></section>
<section className={styles.sectionBlock}><div className={styles.sectionLabel}><MessageCircle/><h2>Beyond Technical Skills</h2></div><div className={styles.cards3}><div className={styles.card}><h3>Problem Solving</h3><p>Breaking complex problems into simple, practical solutions.</p></div><div className={styles.card}><h3>Continuous Learning</h3><p>Always exploring new tools, concepts and technologies.</p></div><div className={styles.card}><h3>Communication</h3><p>Working effectively in teams and presenting ideas clearly.</p></div></div></section>
<section className={styles.ctaBlock}><div><span>BUILD. LEARN. IMPROVE.</span><h2>Let’s Build Something <b>Great Together</b></h2><p>I&apos;m always open to new opportunities, collaborations, and interesting projects.</p></div><Link href="/contact">Get in Touch <ArrowRight size={15}/></Link></section>
</main></PageFrame>}
function ImageFallback(){return <div className={styles.skillsHeroVisualInner}><span>“The more I learn, the more I realize how much more there is to explore.”</span><small>— Nardy Attalla</small><em>Same Engineer.<br/>Bigger Possibilities.</em></div>}
