"use client";

import type { ElementType } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Download, UserRound, MapPin, GraduationCap, BriefcaseBusiness, Mail, Linkedin, Github, Globe2, BrainCircuit, Lightbulb, Users, Rocket } from "lucide-react";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/AboutExact.module.css";

const values = [[BrainCircuit, "Continuous Learning", "I love learning new technologies and exploring how things work under the hood."],[Lightbulb, "Building Real Solutions", "Turning ideas into practical applications that solve real-world problems."],[Users, "Collaboration", "I enjoy working with people, sharing knowledge, and learning from different perspectives."],[Rocket, "Making an Impact", "I’m motivated by using technology to create meaningful and positive change."]] as const;
function SectionHeading({ icon: Icon, title, subtitle }: { icon: ElementType; title: string; subtitle?: string }) {
  return <div className={styles.sectionHeading}><span className={styles.headingBar} /><Icon size={19} strokeWidth={2.2} /><h2>{title}</h2>{subtitle && <em>{subtitle}</em>}</div>;
}
export default function About() {
  return <PageFrame active="About"><main className={styles.aboutPage}>
    <section className={styles.aboutHero}><div className={styles.heroCopy}><div className={styles.kicker}>ABOUT ME</div><h1>More Than<br />Just <span>Code</span></h1><p>I&apos;m Nardy Attalla, a Computer Science Engineer from Egypt, passionate about building real-world applications and exploring the endless possibilities of Machine Learning and AI.</p><div className={styles.heroActions}><a href="/full_stack_cv_edited.pdf" target="_blank" rel="noreferrer" className={styles.primaryButton}><Download size={14} />Download CV</a><Link href="/contact" className={styles.secondaryButton}>Let&apos;s Connect <ArrowRight size={14} /></Link></div></div>
      <div className={styles.heroVisual}><div className={styles.heroSky} /><div className={styles.heroCity} /><div className={styles.heroPyramids} /><div className={styles.heroQuote}><span>“Same engineer.</span><span>Bigger possibilities.”</span><small>— Nardy Attalla</small></div><Image className={styles.heroPortrait} src="/picprofile.png" alt="Nardy Attalla" width={520} height={520} priority /><div className={styles.heroAnnotation}>Curious<br />Learner<br />Problem Solver<br />Builder<i /></div></div>
    </section>
    <section className={styles.storySection}><div className={styles.storyGrid}>
      <div className={styles.storyColumn}><SectionHeading icon={BrainCircuit} title="My Story" subtitle="A journey of curiosity, hard work and continuous learning." /><p>I&apos;m a Computer Science and Engineering graduate from the German University in Cairo (GUC). My journey started with a strong interest in technology and problem-solving, which grew into a passion for building software and exploring how AI can make a real impact.</p><p>Over the past few years, I&apos;ve worked on web and mobile applications, completed internships, and built machine learning and computer vision projects. I&apos;m turning ideas into practical solutions and I&apos;m always eager to learn new technologies and take on challenging projects.</p><p>I&apos;m currently focusing on deepening my knowledge in Machine Learning, MLOps and RAG, while continuing to build high-quality software and collaborate with amazing people.</p><div className={styles.storyQuote}><p>“I believe in consistent progress, practical projects, and never stopping the learning journey.”</p><small>— Nardy Attalla</small></div></div>
      <div className={styles.personalColumn}><SectionHeading icon={UserRound} title="Personal Details" /><div className={styles.personalCard}><div className={styles.detailRow}><UserRound /><span>Nardy Attalla</span></div><div className={styles.detailRow}><MapPin /><span>Cairo, Egypt (From Sohag)</span></div><div className={styles.detailRow}><GraduationCap /><span>B.Sc. Computer Science and Engineering<br /><b>German University in Cairo (GUC)</b><br />2021 – 2025</span></div><div className={styles.detailRow}><BriefcaseBusiness /><span>Open to opportunities worldwide</span></div><a className={styles.detailRow} href="mailto:nardy.attalla@gmail.com"><Mail /><span>nardy.attalla@gmail.com</span></a><a className={styles.detailRow} href="https://www.linkedin.com/in/nardy-attallah" target="_blank" rel="noreferrer"><Linkedin /><span>linkedin.com/in/nardy-attallah</span></a><a className={styles.detailRow} href="https://github.com/Nardy11" target="_blank" rel="noreferrer"><Github /><span>github.com/Nardy11</span></a></div></div>
      <div className={styles.polaroids}><div className={styles.polaroidBerlin}><div className={styles.polaroidImage} /><span>Semester<br />abroad in<br />Berlin</span><i /></div><div className={styles.polaroidCity}><div className={styles.cityImage} /></div><p className={styles.polaroidCaption}>“New places,<br />new perspectives,<br />same passion.”</p></div>
    </div></section>
    <section className={styles.drivesSection}><SectionHeading icon={BrainCircuit} title="What Drives Me" subtitle="The values and interests that keep me motivated." /><div className={styles.valueGrid}>{values.map(([Icon,title,text])=><article className={styles.valueCard} key={title}><Icon size={28}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.connectSection}><SectionHeading icon={Mail} title="Let&apos;s Connect" subtitle="I&apos;m always open to interesting conversations, collaborations, and opportunities." /><div className={styles.connectGrid}><div className={styles.connectLinks}><a href="mailto:nardy.attalla@gmail.com"><Mail/><span>Email</span><b>nardy.attalla@gmail.com</b></a><a href="https://www.linkedin.com/in/nardy-attallah" target="_blank" rel="noreferrer"><Linkedin/><span>LinkedIn</span><b>linkedin.com/in/nardy-attallah</b></a><a href="https://github.com/Nardy11" target="_blank" rel="noreferrer"><Github/><span>GitHub</span><b>github.com/Nardy11</b></a><a href="#opportunities"><MapPin/><span>Location</span><b>Cairo, Egypt</b></a><Link href="/contact" className={styles.opportunityButton}><Globe2/>Open to opportunities worldwide</Link></div><div className={styles.messageCard}><div className={styles.formRow}><input placeholder="Your Name" aria-label="Your Name"/><input placeholder="Your Email" aria-label="Your Email" type="email"/></div><textarea placeholder="Your Message" aria-label="Your Message"/><button type="button">Send Message <ArrowRight size={14}/></button></div><div className={styles.connectArt}><div className={styles.earth}/><div className={styles.connectNote}>Let&apos;s build<br />something<br />great together!<i/></div></div></div></section>
  </main></PageFrame>;
}