import type { ElementType } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Github, Linkedin, Mail, MapPin, GraduationCap, BrainCircuit, Lightbulb, Users, Rocket, Dumbbell, Plane, Camera, Gamepad2 } from "lucide-react";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/PortfolioPages.module.css";

export default function About(){return <PageFrame active="About"><main className={styles.container}>
<section className={styles.aboutHero}><div><div className={styles.kicker}>ABOUT ME</div><h1 className={styles.sectionTitle} style={{fontSize:54}}>More Than<br/>Just <span className={styles.gradient}>Code</span></h1><p className={styles.sectionIntro}>I&apos;m Nardy Attalla, a Computer Science Engineer from Egypt, passionate about building real-world applications and exploring the possibilities of Machine Learning and AI.</p><div className={styles.heroButtons}><a href="/full_stack_cv_edited.pdf" target="_blank" className={styles.button}>Download CV</a><Link href="/contact" className={styles.buttonGhost}>Let’s Connect <ArrowRight size={14}/></Link></div></div><div className={styles.aboutPhoto}><Image src="/picprofile.png" alt="Nardy Attalla" width={500} height={500}/><span className={styles.aboutAnnotation}>Curious Learner<br/>Problem Solver<br/>Builder</span></div></section>
<section className={styles.sectionBlock}><div className={styles.aboutGrid}><div><div className={styles.sectionLabel}><BrainCircuit/><h2>My Story</h2><span>A journey of curiosity, hard work and continuous learning.</span></div><p className={styles.sectionIntro}>I&apos;m a Computer Science and Engineering graduate from the German University in Cairo (GUC). My journey started with a strong interest in technology and problem-solving, which grew into a passion for building software and exploring how AI can make a real impact.</p><p className={styles.sectionIntro}>Over the past few years, I&apos;ve worked on web and mobile applications, completed internships, and built machine learning and computer vision projects. I&apos;m continuing to deepen my knowledge while building practical software and learning from challenging projects.</p><div className={styles.quoteCard}>“I believe in consistent progress, practical projects, and never stopping the learning journey.”<small>— Nardy Attalla</small></div></div><div className={styles.personalCard}><h3>Personal Details</h3><p><MapPin/> Cairo, Egypt (From Sohag)</p><p><GraduationCap/> B.Sc. Computer Science and Engineering — GUC, 2021–2025</p><p><Mail/> nardy.attalla@gmail.com</p><p><Linkedin/> linkedin.com/in/nardy-attallah</p><p><Github/> github.com/Nardy11</p></div></div></section>
<section className={styles.sectionBlock}><div className={styles.sectionLabel}><Rocket/><h2>What Drives Me</h2></div><div className={styles.cards4}>{[[BrainCircuit,"Continuous Learning","I love learning new technologies and exploring how things work under the hood."],[Lightbulb,"Building Real Solutions","Turning ideas into practical applications that solve real-world problems."],[Users,"Collaboration","I enjoy working with people, sharing knowledge, and learning from different perspectives."],[Rocket,"Making an Impact","I’m motivated by using technology to create meaningful and positive change."]].map(([I,t,p])=>{const Icon=I as ElementType;return <div className={styles.card} key={String(t)}><Icon size={25}/><h3>{String(t)}</h3><p>{String(p)}</p></div>})}</div></section>
<section className={styles.sectionBlock}><div className={styles.sectionLabel}><Camera/><h2>Beyond Code</h2><span>Some things I enjoy outside of programming.</span></div><div className={styles.hobbyGrid}>{[[Dumbbell,"Fitness","/Distance_stereo.jpeg"],[Plane,"Travel","/normal_navigation.png"],[Camera,"Photography","/CV.webp"],[Gamepad2,"Gaming","/Diablo.png"]].map(([I,t,img])=>{const Icon=I as ElementType;return <article key={String(t)}><Image src={String(img)} alt="" fill/><div><Icon/><h3>{String(t)}</h3><p>Keeping curiosity and creativity active beyond code.</p></div></article>})}</div></section>
<section className={styles.sectionBlock}><div className={styles.sectionLabel}><Mail/><h2>Let&apos;s Connect</h2><span>I&apos;m always open to interesting conversations, collaborations, and opportunities.</span></div><div className={styles.aboutContact}><div><a href="mailto:nardy.attalla@gmail.com">Email <b>nardy.attalla@gmail.com</b></a><a href="https://www.linkedin.com/in/nardy-attallah" target="_blank" rel="noreferrer">LinkedIn <b>linkedin.com/in/nardy-attallah</b></a><a href="https://github.com/Nardy11" target="_blank" rel="noreferrer">GitHub <b>github.com/Nardy11</b></a></div><Link href="/contact" className={styles.button}>Send a Message <ArrowRight size={14}/></Link></div></section>
</main></PageFrame>}