import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Github, Linkedin, Mail, MapPin, GraduationCap } from "lucide-react";
import { PageFrame } from "@/components/PortfolioPages";
import styles from "@/components/PortfolioPages.module.css";
export default function About(){return <PageFrame active="About"><main className={styles.container}>
<section className={styles.aboutHero}><div><div className={styles.kicker}>ABOUT ME</div><h1 className={styles.sectionTitle} style={{fontSize:54}}>More Than<br/>Just <span className={styles.gradient}>Code</span></h1><p className={styles.sectionIntro}>I’m Nardy Attalla, a Computer Science Engineer from Egypt, passionate about building real-world applications and exploring the possibilities of Machine Learning and AI.</p><div style={{display:"flex",gap:12,marginTop:24}}><a href="/full_stack_cv_edited.pdf" target="_blank" className={styles.button}>Download CV</a><Link href="/contact" className={styles.buttonGhost}>Let’s Connect <ArrowRight size={14}/></Link></div></div><div className={styles.aboutPhoto}><Image src="/picprofile.png" alt="Nardy Attalla" width={500} height={500}/></div></section>
<section className={styles.sectionBlock}><div className={styles.aboutGrid}><div><h2 className={styles.sectionTitle}>My Story</h2><p className={styles.sectionIntro}>I’m a Computer Science and Engineering graduate from the German University in Cairo (GUC). My journey started with a strong interest in technology and problem-solving, which grew into a passion for building software and exploring how AI can make a real impact.</p><p className={styles.sectionIntro}>I’ve worked on web and mobile applications, completed internships, and built machine learning and computer vision projects. I’m continuing to deepen my knowledge while building practical software and learning from challenging projects.</p></div><div className={styles.card}><h3>Personal Details</h3><p><MapPin size={14}/> Cairo, Egypt</p><p><GraduationCap size={14}/> B.Sc. Computer Science and Engineering — GUC, 2021–2025</p><p><Mail size={14}/> nardy.attalla@gmail.com</p><p><Linkedin size={14}/> linkedin.com/in/nardy-attallah</p><p><Github size={14}/> github.com/Nardy11</p></div></div></section>
<section className={styles.sectionBlock}><h2 className={styles.sectionTitle}>What Drives Me</h2><div className={styles.cards4}><div className={styles.card}><h3>Continuous Learning</h3><p>Learning new technologies and exploring how things work.</p></div><div className={styles.card}><h3>Building Real Solutions</h3><p>Turning ideas into practical applications that solve problems.</p></div><div className={styles.card}><h3>Collaboration</h3><p>Working with people, sharing knowledge and learning from different perspectives.</p></div><div className={styles.card}><h3>Making an Impact</h3><p>Using technology to create meaningful and positive change.</p></div></div></section>
<section className={styles.sectionBlock}><h2 className={styles.sectionTitle}>Beyond Code</h2><div className={styles.cards4}><div className={styles.card}><h3>Fitness</h3><p>Staying focused and energized.</p></div><div className={styles.card}><h3>Travel</h3><p>Exploring new places and cultures.</p></div><div className={styles.card}><h3>Photography</h3><p>Capturing moments and perspectives.</p></div><div className={styles.card}><h3>Gaming</h3><p>A way to relax and stay creative.</p></div></div></section>
</main></PageFrame>}