"use client";
import { Download, Github, Linkedin, Mail, Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import styles from "./PortfolioPages.module.css";
const links=[["Home","/home"],["Projects","/projects"],["Experience","/experience"],["Skills","/skills"],["About","/about"],["Contact","/contact"]] as const;
export default function SiteHeader({active,interactive=false}:{active?:string;interactive?:boolean}){const pathname=usePathname();const[dark,setDark]=useState(true);useEffect(()=>{document.documentElement.style.colorScheme=dark?"dark":"light"},[dark]);return <header className={styles.header}><a href="/home" className={styles.brand}><span className={styles.brandMark}>NA</span><span className={styles.brandText}><b>Nardy Attalla</b><small>CS Engineer | Aspiring ML Engineer</small></span></a><nav className={styles.mainNav}>{links.map(([label,href])=><a key={label} className={(active===label||pathname===href)?styles.active:""} href={href}>{label}</a>)}</nav><div className={styles.headerActions}><button className={styles.themeButton} aria-label="Toggle theme" onClick={()=>setDark(v=>!v)}>{dark?<Moon size={16}/>:<Sun size={16}/>}</button>{interactive&&<a href="/cv" className={styles.modeButton}>✋ CV Mode</a>}{interactive&&<a href="/nlp" className={styles.modeButton}>✣ NLP Assistant</a>}<a href="/full_stack_cv_edited.pdf" target="_blank" rel="noreferrer" className={styles.headerCv}><Download size={15}/> Download CV</a></div></header>}
export function Footer(){return <footer className={styles.footer}><div className={styles.footerBrand}><span className={styles.brandMark}>NA</span><div><b>Nardy Attalla</b><small>CS Engineer | Aspiring ML Engineer</small></div></div><div className={styles.footerQuote}>“Build. Learn. Improve. Repeat.”</div><div className={styles.socials}><a href="https://github.com/Nardy11" target="_blank" rel="noreferrer"><Github size={18}/></a><a href="https://www.linkedin.com/in/nardy-attallah" target="_blank" rel="noreferrer"><Linkedin size={18}/></a><a href="mailto:nardy.attalla@gmail.com"><Mail size={18}/></a></div></footer>}
export function PageFrame({active,children,interactive=false}:{active:string;children:React.ReactNode;interactive?:boolean}){return <div className={styles.page}><SiteHeader active={active} interactive={interactive}/>{children}<Footer/></div>}
