services:
  - type: web
    name: ai-portfolio-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:main_app --host 0.0.0.0 --port $PORT
    autoDeploy: true
